# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 9000
    servlet:
        context-path: /ura

spring:
  profiles:
    active: common, core, shop