# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 9001
    servlet:
        context-path: /ura

spring:
  profiles:
    active: common, core, ai
logging:
  config: ura-ai/src/main/resources/log4j.properties

#logging:
#  level:
#    root: ERROR
#    org.springframework: ERROR
#    com.ura.ai: DEBUG