server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9090
  servlet:
    context-path: /ura

spring:
  profiles:
    active: common,admin

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.mybatis: ERROR
    com.ura.admin: DEBUG
    com.ura: ERROR